#pragma once

// スクリーンサイズ(クライアント領域)
#define SCREEN_WIDTH  (1024)	// 幅
#define SCREEN_HEIGHT (576)		// 高さ

// 重力
#define GRAVITY (9.8f / 2)

// 衝突対象
enum eDirection
{
	DIRECTION_NONE,
	DIRECTION_UP,
	DIRECTION_UPRIGHT,
	DIRECTION_RIGHT,
	DIRECTION_DOWNRIGHT,
	DIRECTION_DOWN,
	DIRECTION_DOWNLEFT,
	DIRECTION_LEFT,
	DIRECTION_UPLEFT
};
// 衝突対象
enum eCollision
{
	COLLISION_NONE,
	COLLISION_GROUND,
	COLLISION_WALL,
	COLLISION_CEILING
};