
#ifndef TEXTURE_H_
#define TEXTURE_H_

#include <d3d9.h>

#define SIZE_1024	(1024)
#define SIZE_576	(576)
#define SIZE_512	(512)
#define SIZE_256	(256)
#define SIZE_128	(128)
#define SIZE_64		(64)
#define SIZE_2		(2)

// テクスチャ管理番号
enum TextureIndex
{
	// テストライト
	TEXTURE_INDEX_TEST1,
	// ゲーム
	// 背景
	TEXTURE_INDEX_BACK1,
	TEXTURE_INDEX_BACK2,
	TEXTURE_INDEX_BACK3,
	TEXTURE_INDEX_BACK4,
	TEXTURE_INDEX_BACK5,
	TEXTURE_INDEX_BACK6,
	TEXTURE_INDEX_BACK7,
	// キャラクター
	TEXTURE_INDEX_BABY,
	TEXTURE_INDEX_SEIKA,
	TEXTURE_INDEX_YA,
	// ギミック
	TEXTURE_INDEX_CANDLE1,
	TEXTURE_INDEX_CANDLE2,
	TEXTURE_INDEX_GROUND,
	TEXTURE_INDEX_GOAL1,
	TEXTURE_INDEX_GOAL2,
	TEXTURE_INDEX_GHOST,

	// シーン-----------------------------------------------------
	// 共通
	TEXTURE_INDEX_BLACK,
	TEXTURE_INDEX_BACK,
	TEXTURE_INDEX_DECISION,

	//タイトル
	TEXTURE_INDEX_BG,
	TEXTURE_INDEX_KOUMEITOU,
	TEXTURE_INDEX_UNKO,
	TEXTURE_INDEX_LIGHT,
	TEXTURE_INDEX_PURESENTER,
	TEXTURE_INDEX_TITLE,

	//人数
	TEXTURE_INDEX_PEOPLE_HEADING,
	TEXTURE_INDEX_PEOPLE_LIGHT,
	TEXTURE_INDEX_PEOPLE_ONE,
	TEXTURE_INDEX_PEOPLE_TWO,
	TEXTURE_INDEX_PEOPLE_THREE,
	TEXTURE_INDEX_PEOPLE_FOUR,

	//キャラクター
	TEXTURE_INDEX_CHARACTER_HEADING,
	TEXTURE_INDEX_CHARACTER_LIGHT,
	TEXTURE_INDEX_CHARACTER_SELECT,
	TEXTURE_INDEX_CHARACTER_ONE,
	TEXTURE_INDEX_CHARACTER_TWO,
	TEXTURE_INDEX_CHARACTER_THREE,
	TEXTURE_INDEX_CHARACTER_FOUR,
	TEXTURE_INDEX_CHARACTER,

	//名前

	//難易度
	TEXTURE_INDEX_DIFFICULTY_HEADING,
	TEXTURE_INDEX_DIFFICULTY_LIGHT,
	TEXTURE_INDEX_DIFFICULTY_EASY,
	TEXTURE_INDEX_DIFFICULTY_NORMAL,
	TEXTURE_INDEX_DIFFICULTY_HARD,

	// STAGE
	TEXTURE_INDEX_STAGE_HEADING,
	TEXTURE_INDEX_STAGE_ROPE,
	TEXTURE_INDEX_STAGE_CHARACTER,
	TEXTURE_INDEX_BLACKNUMBER,

	// ゲームオーバー
	TEXTURE_INDEX_GAMEOVER1,
	TEXTURE_INDEX_GAMEOVER2,
	TEXTURE_INDEX_GAMEOVER3,
	TEXTURE_INDEX_GAMEOVER4,

	// ゲームクリア
	TEXTURE_INDEX_GAMECLEAR,

	TEXTURE_INDEX_MAX
};

// テクスチャの読み込み
//
// 戻り値:読み込めなかった数
//
int Texture_Load(void);

// テクスチャの解放
void Texture_Release(void);

// テクスチャインターフェースの取得
//
// 戻り値:テクスチャインターフェース
//        ただし存在しないindexを指定した場合、NULL
LPDIRECT3DTEXTURE9 Texture_GetTexture(TextureIndex index);

// テクスチャ解像度幅の取得
//
// 引数 ... index テクスチャ管理番号
//
int Texture_GetWidth(TextureIndex index);

// テクスチャ解像度高さの取得
//
// 引数 ... index テクスチャ管理番号
//
int Texture_GetHeight(TextureIndex index);


#endif // TEXTURE_H_