
#ifndef TEXTURE_H_
#define TEXTURE_H_

#include <d3d9.h>

#define SIZE_1024	(1024)
#define SIZE_576	(576)
#define SIZE_512	(512)
#define SIZE_256	(256)
#define SIZE_128	(128)
#define SIZE_64		(64)
#define SIZE_2		(2)

// テクスチャ管理番号
enum TextureIndex
{
	// 共通
	TEXTURE_INDEX_BLACK,
	TEXTURE_INDEX_BACK,
	TEXTURE_INDEX_DECISION,

	//タイトル
	TEXTURE_INDEX_BG,
	TEXTURE_INDEX_KOUMEITOU,
	TEXTURE_INDEX_UNKO,
	TEXTURE_INDEX_LIGHT,
	TEXTURE_INDEX_PURESENTER,
	TEXTURE_INDEX_TITLE,

	// ステージ選択
	TEXTURE_INDEX_STAGE_HEADING,
	TEXTURE_INDEX_STAGE_ROPE,
	TEXTURE_INDEX_BLACKNUMBER,

	// ゲーム
	// 背景
	TEXTURE_INDEX_BACK1,
	TEXTURE_INDEX_BACK2,
	TEXTURE_INDEX_BACK3,
	TEXTURE_INDEX_BACK4,
	TEXTURE_INDEX_BACK5,
	TEXTURE_INDEX_BACK6,
	TEXTURE_INDEX_BACK7,
	// キャラクター
	TEXTURE_INDEX_BABY,
	TEXTURE_INDEX_SEIKA,
	TEXTURE_INDEX_HINOKO,
	TEXTURE_INDEX_YA,

	//プレイヤー右
	TEXTURE_INDEX_PLAYER_R0,
	TEXTURE_INDEX_PLAYER_R1,
	TEXTURE_INDEX_PLAYER_R2,
	TEXTURE_INDEX_PLAYER_R3,
	TEXTURE_INDEX_PLAYER_R4,
	TEXTURE_INDEX_PLAYER_R5,
	TEXTURE_INDEX_PLAYER_R6,
	TEXTURE_INDEX_PLAYER_R7,
	TEXTURE_INDEX_PLAYER_R8,
	TEXTURE_INDEX_PLAYER_R9,
	TEXTURE_INDEX_PLAYER_R10,
	TEXTURE_INDEX_PLAYER_R11,
	TEXTURE_INDEX_PLAYER_R12,
	TEXTURE_INDEX_PLAYER_R13,
	TEXTURE_INDEX_PLAYER_R14,
	TEXTURE_INDEX_PLAYER_R15,
	TEXTURE_INDEX_PLAYER_R16,
	TEXTURE_INDEX_PLAYER_R17,
	TEXTURE_INDEX_PLAYER_R18,
	//プレイヤー左
	TEXTURE_INDEX_PLAYER_L0,
	TEXTURE_INDEX_PLAYER_L1,
	TEXTURE_INDEX_PLAYER_L2,
	TEXTURE_INDEX_PLAYER_L3,
	TEXTURE_INDEX_PLAYER_L4,
	TEXTURE_INDEX_PLAYER_L5,
	TEXTURE_INDEX_PLAYER_L6,
	TEXTURE_INDEX_PLAYER_L7,
	TEXTURE_INDEX_PLAYER_L8,
	TEXTURE_INDEX_PLAYER_L9,
	TEXTURE_INDEX_PLAYER_L10,
	TEXTURE_INDEX_PLAYER_L11,
	TEXTURE_INDEX_PLAYER_L12,
	TEXTURE_INDEX_PLAYER_L13,
	TEXTURE_INDEX_PLAYER_L14,
	TEXTURE_INDEX_PLAYER_L15,
	TEXTURE_INDEX_PLAYER_L16,
	TEXTURE_INDEX_PLAYER_L17,
	TEXTURE_INDEX_PLAYER_L18,

	// ギミック
	TEXTURE_INDEX_CANDLE1,
	TEXTURE_INDEX_CANDLE2,
	TEXTURE_INDEX_GROUND,
	TEXTURE_INDEX_GOAL1,
	TEXTURE_INDEX_GOAL2,
	TEXTURE_INDEX_GHOST,

	// 操作方法
	TEXTURE_INDEX_CONTROL,

	// ゲームオーバー
	TEXTURE_INDEX_GAMEOVER1,
	TEXTURE_INDEX_GAMEOVER2,
	TEXTURE_INDEX_GAMEOVER3,
	TEXTURE_INDEX_GAMEOVER4,

	// ゲームクリア
	TEXTURE_INDEX_GAMECLEAR,

	// 戻る
	TEXTURE_INDEX_RETURN,
	TEXTURE_INDEX_TOTITLE,
	TEXTURE_INDEX_TOSTAGE,
	TEXTURE_INDEX_RETURNSELECT,

	TEXTURE_INDEX_MAX
};

// テクスチャの読み込み
//
// 戻り値:読み込めなかった数
//
int Texture_Load(void);

// テクスチャの解放
void Texture_Release(void);

// テクスチャインターフェースの取得
//
// 戻り値:テクスチャインターフェース
//        ただし存在しないindexを指定した場合、NULL
LPDIRECT3DTEXTURE9 Texture_GetTexture(TextureIndex index);

// テクスチャ解像度幅の取得
//
// 引数 ... index テクスチャ管理番号
//
int Texture_GetWidth(TextureIndex index);

// テクスチャ解像度高さの取得
//
// 引数 ... index テクスチャ管理番号
//
int Texture_GetHeight(TextureIndex index);


#endif // TEXTURE_H_